# Generated by Django 4.2.2 on 2023-06-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='disliked', to='studentres.signup'),
        ),
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked', to='studentres.signup'),
        ),
        migrations.AddField(
            model_name='signup',
            name='profile_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
