# Generated by Django 4.2.2 on 2023-06-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentres', '0002_notes_dislikes_notes_likes_signup_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='profile_photo',
        ),
    ]
