# Generated by Django 4.2.2 on 2023-06-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentres', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='description',
        ),
    ]
