# Generated by Django 4.2.2 on 2023-06-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentres', '0005_rename_text_review_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='notes',
            new_name='note',
        ),
    ]
